version: '2'

services:
  # note that the app container does NOT remain running - this is on purpose.
  # use the `makefile` to build/run/test the container as needed
  awscli:
    build:
      context: dockerfiles/awscli
      dockerfile: Dockerfile
  terraform:
    build:
      context: dockerfiles/terraform
      dockerfile: Dockerfile
  